package enums;
public enum RequestsForStudent {
	REQUESTFORSERVICEDESK,MAKEID,CONFIRMATIONOFPLACEOFSTUDY,MAKEONAY,MILITARYREGISTRATION,
	TRANSCRIPTFORACADEMICYEAR,REQUESTFORFX,RETAKECOURSE,MEDICALAPPLICATION;
}